
---
# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: R-CMD-check-macos ğŸ“¦

on:
  # 'push' events are triggered when commits
  # are pushed to one of these branches
  push:
    branches:
      - main
      - cran_mac
    tags:
      - "v*"
  # 'pull_request' events are triggered when PRs are
  # created against one of these target branches.
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
    branches:
      - main
  # 'workflow_dispatch' gives you the ability
  # to run this workflow on demand, anytime
  workflow_dispatch:

jobs:
  check:
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: no
      matrix:
        config:
          - { os: macOS-14, r: "release" }
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      _R_CHECK_FORCE_SUGGESTS_: no
      LC_CTYPE: en_GB.UTF-8
      RMPI_TYPE: OPENMPI
      R_BROWSER: no
      R_PDFVIEWER: no
      _R_CHECK_INSTALL_DEPENDS_: yes
      _R_CHECK_NO_RECOMMENDED_: yes
      _R_CHECK_TIMINGS_: 10
      _R_CHECK_DEPRECATED_DEFUNCT_: yes
      _R_CHECK_CODE_ASSIGN_TO_GLOBALENV_: yes
      _R_CHECK_CODE_DATA_INTO_GLOBALENV_: yes
      _R_CHECK_SCREEN_DEVICE_: warn
      _R_CHECK_S3_METHODS_NOT_REGISTERED_: yes
      _R_CHECK_OVERWRITE_REGISTERED_S3_METHODS_: yes
      _R_CHECK_NATIVE_ROUTINE_REGISTRATION_: yes
      _R_CHECK_FF_CALLS_: registration
      _R_CHECK_PRAGMAS_: yes
      _R_CHECK_COMPILATION_FLAGS_: yes
      _R_CHECK_COMPILATION_FLAGS_KNOWN_: "-Wconversion -Wno-sign-conversion"
      _R_CHECK_THINGS_IN_TEMP_DIR_: yes
      _R_CHECK_THINGS_IN_TEMP_DIR_EXCLUDE_: "^(ompi|dsymutil)"
      _R_CHECK_MATRIX_DATA_: yes
      _R_CHECK_ORPHANED_: yes
      _R_CHECK_BROWSER_NONINTERACTIVE_: yes
      _R_CHECK_MBCS_CONVERSION_FAILURE_: yes
      _R_CHECK_RD_VALIDATE_RD2HTML_: yes
      _R_CHECK_RD_MATH_RENDERING_: yes
      _R_CHECK_VALIDATE_UTF8_: yes
      R_DEFAULT_INTERNET_TIMEOUT: 600
      NOAWT: 1
      RGL_USE_NULL: yes
      WNHOME:   /usr/local/wordnet-3.1
      _R_CHECK_XREFS_USE_ALIASES_FROM_CRAN_:   yes
      _R_CHECK_RD_VALIDATE_RD2HTML_: yes
      _R_CHECK_RD_MATH_RENDERING_:   yes
      _R_CHECK_VIGNETTES_SKIP_RUN_MAYBE_:   yes
      _R_CHECK_TESTS_NLINES_: 0
      _R_CHECK_VIGNETTES_NLINES_: 0

    if: >
      !contains(github.event.commits[0].message, '[skip checks]')
    steps:
      - name: Checkout repository ğŸ›
        uses: actions/checkout@v4

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R ğŸ“Š
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: yes

      - name: Install R package dependencies ğŸ“¦
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck

      - name: Run R CMD check ğŸ¯
        uses: r-lib/actions/check-r-package@v2
